#!/bin/bash

set -ex

OUT_FOLDER=$1
YEAR=$2
MONTH=$3
DAY=$4
DATE=$2$3$4
DATE_SLASH=$2/$3/$4

IN_FILE=${OUT_FOLDER}/$DATE.wav
OUT_FILE_PREFIX=${OUT_FOLDER}/$DATE
OUT_AUDIO=${OUT_FILE_PREFIX}.mp3
OUT_AUDIO_NORMALIZED=${OUT_FILE_PREFIX}.normalized.wav
OUT_IMAGE=${OUT_FILE_PREFIX}.png
OUT_VIDEO=${OUT_FILE_PREFIX}.mp4

# normalize audio
cp -v "$IN_FILE" "$OUT_AUDIO_NORMALIZED"
normalize-audio "$OUT_AUDIO_NORMALIZED"

# convert wav to mp3
ffmpeg -y -loglevel warning -i "$OUT_AUDIO_NORMALIZED" -acodec libmp3lame -ab 64k "$OUT_AUDIO"

# create timestamp watermark
convert -pointsize 240 -background red -fill yellow -font DejaVu-Sans-Bold label:"$DATE_SLASH" "$OUT_IMAGE"

# use watermark as static "video"
ffmpeg -y -loglevel warning -loop 1 -i "$OUT_IMAGE" -i "$OUT_AUDIO" -c:a copy -c:v libx264 -shortest "$OUT_VIDEO"
