#!/bin/bash

set -ex

IN_FOLDER=$1
OUT_FOLDER=$2
YEAR=$3
MONTH=$4
DAY=$5
DATE=$3$4$5
DATE_SLASH=$3/$4/$5

IN_FILE=$IN_FOLDER/$DATE.mid
OUT_FILE_PREFIX=$OUT_FOLDER/$DATE
OUT_AUDIO=${OUT_FILE_PREFIX}.wav
OUT_AUDIO_MP3=${OUT_FILE_PREFIX}.mp3
OUT_IMAGE=${OUT_FILE_PREFIX}.png
OUT_VIDEO_ONLY=${OUT_FILE_PREFIX}.vid.mp4
OUT_VIDEO=${OUT_FILE_PREFIX}.mp4

# render midi to audio
fluidsynth -nli -r 44100 -o synth.cpu-cores=2 -Twav -F"$OUT_AUDIO" /usr/share/sounds/sf2/MuseScore_General_Full.sf2 "$IN_FILE"

# normalize audio
normalize-audio "$OUT_AUDIO"

# wav -> mp3
ffmpeg -loglevel warning -y -i "$OUT_AUDIO" -vn -ar 44100 -ac 2 -b:a 192k "$OUT_AUDIO_MP3"

# render midi to video
## TODO: start dummy x-server only if DISPLAY variable not set
X :0 -config /sisy/video-dummy.conf &
echo $DISPLAY
DISPLAY="${DISPLAY:-:0}" /sisy/MIDIVisualizer/build/MIDIVisualizer --midi "$IN_FILE" --size 1920 1080 --preroll 0 --postroll 3 --export "$OUT_VIDEO_ONLY" --format MPEG4 --color-keyboard 0 1 1 --color-particles 1 0 0 --color-pedal 0 1 0 --color-major 0 0 1 --color-minor 1 0 0 --color-wave 0 1 0 --color-bg 0.3 0 0

# create timestamp watermark
convert -pointsize 64 -font DejaVu-Sans-Bold -background none -fill white label:"$DATE_SLASH" "$OUT_IMAGE"

# combine video+watermark and audio
ffmpeg -y -loglevel warning -i "$OUT_VIDEO_ONLY" -i "$OUT_IMAGE" -filter_complex "overlay=W-w-10:10" -i "$OUT_AUDIO_MP3" -codec:a copy "$OUT_VIDEO"

# TODO: append picture to the end of the video
## jpg to mp4
# ffmpeg -loop 1 -i 20210412.pic.jpg -c:v libx264 -t 3 -pix_fmt yuv420p -vf scale=1920:1080 20210412.pic.mp4

## add silent mp3
# ffmpeg -ar 44100 -acodec pcm_s16le -f s16le -ac 2 -channel_layout 2.1 -i /dev/zero -i 20210412.pic.mp4 -vcodec copy -acodec libmp3lame -shortest 20210412.pic.sound.mp4

## concat videos
# ffmpeg -i 20210412.mid.mp4 -i 20210412.pic.sound.mp4 -filter_complex "[0]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1[v0];[1]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1[v1];[v0][0:a:0][v1][1:a:0]concat=n=2:v=1:a=1[v][a]" -map "[v]" -map "[a]" 20210412.mp4
