#!/bin/bash

IN_FOLDER=$1
OUT_FOLDER=$2
YEAR=$3
MONTH=$4
DAY=$5
DATE=$3$4$5
DATE_SLASH=$3/$4/$5

IN_FILE=$IN_FOLDER/$DATE.mid
OUT_FILE_PREFIX=$OUT_FOLDER/$DATE
OUT_AUDIO=${OUT_FILE_PREFIX}.ogg
OUT_IMAGE=${OUT_FILE_PREFIX}.png
OUT_VIDEO=${OUT_FILE_PREFIX}.mp4

set -x

fluidsynth -nli -r 48000 -o synth.cpu-cores=2 -T oga -F "$OUT_AUDIO" /usr/share/sounds/sf2/MuseScore_General_Full.sf2 "$IN_FILE"
convert -pointsize 960 -font Noto-Mono label:"$DATE_SLASH" "$OUT_IMAGE"
ffmpeg -y -loglevel warning -loop 1 -i "$OUT_IMAGE" -i "$OUT_AUDIO" -c:a copy -c:v libx264 -shortest "$OUT_VIDEO"
