#!/bin/bash

set -x

IN_FOLDER=$1
OUT_FOLDER=$2
YEAR=$3
MONTH=$4
DAY=$5
DATE=$3$4$5
DATE_SLASH=$3/$4/$5

IN_FILE=$IN_FOLDER/$DATE.wav
OUT_FILE_PREFIX=$OUT_FOLDER/$DATE
OUT_AUDIO=${OUT_FILE_PREFIX}.mp3
OUT_IMAGE=${OUT_FILE_PREFIX}.png
OUT_VIDEO=${OUT_FILE_PREFIX}.mp4

# convert wav to mp3
ffmpeg -y -loglevel warning -i "$IN_FILE" -acodec libmp3lame -ab 64k "$OUT_AUDIO"

# create timestamp watermark
convert -pointsize 960 -background red -fill yellow -font DejaVu-Sans-Bold label:"$DATE_SLASH" "$OUT_IMAGE"

# use watermark as static "video"
ffmpeg -y -loglevel warning -loop 1 -i "$OUT_IMAGE" -i "$OUT_AUDIO" -c:a copy -c:v libx264 -shortest "$OUT_VIDEO"
