#!/bin/bash

set -x

IN_FOLDER=$1
OUT_FOLDER=$2
YEAR=$3
MONTH=$4
DAY=$5
DATE=$3$4$5
DATE_SLASH=$3/$4/$5

IN_FILE=$IN_FOLDER/$DATE.mid
OUT_FILE_PREFIX=$OUT_FOLDER/$DATE
OUT_AUDIO=${OUT_FILE_PREFIX}.mp3
OUT_IMAGE=${OUT_FILE_PREFIX}.png
OUT_VIDEO=${OUT_FILE_PREFIX}.mp4
OUT_VIDEO_ONLY=${OUT_FILE_PREFIX}.vid.mp4

# render midi to audio
fluidsynth -nli -r 44100 -o synth.cpu-cores=2 -T raw -F- /usr/share/sounds/sf2/MuseScore_General_Full.sf2 "$IN_FILE" | ffmpeg -y -loglevel warning -f s32le -i - "$OUT_AUDIO"

# render midi to video
X :0 -config /sisy/video-dummy.conf &
DISPLAY=:0 /sisy/MIDIVisualizer/build/MIDIVisualizer --midi "$IN_FILE" --size 1920 1080 --preroll 0 --postroll 3 --export "$OUT_VIDEO_ONLY" --format MPEG4 --color-keyboard 0 0 1 --color-particles 1 0 0 --color-pedal 0 1 0 --color-major 0 0 1 --color-minor 1 0 0

# create timestamp watermark
convert -pointsize 64 -font DejaVu-Sans-Bold -background none -fill white label:"$DATE_SLASH" "$OUT_IMAGE"

# combine video+watermark and audio
ffmpeg -y -loglevel warning -i "$OUT_VIDEO_ONLY" -i "$OUT_IMAGE" -filter_complex "overlay=W-w-10:10" -i "$OUT_AUDIO" -codec:a copy "$OUT_VIDEO"
