#!/bin/bash

IN_FOLDER=$1
OUT_FOLDER=$2
YEAR=$3
MONTH=$4
DAY=$5
DATE=$3$4$5
DATE_SLASH=$3/$4/$5

IN_FILE=$IN_FOLDER/$DATE.mid
OUT_FILE_PREFIX=$OUT_FOLDER/$DATE
OUT_AUDIO=${OUT_FILE_PREFIX}.ogg
OUT_IMAGE=${OUT_FILE_PREFIX}.png
OUT_VIDEO=${OUT_FILE_PREFIX}.mp4
OUT_VIDEO_ONLY=${OUT_FILE_PREFIX}.vid.mp4

set -x

# render midi to audio
fluidsynth -nli -r 48000 -o synth.cpu-cores=2 -T oga -F "$OUT_AUDIO" /usr/share/sounds/sf2/MuseScore_General_Full.sf2 "$IN_FILE"

# render midi to video
X :0 -config /build/video-dummy.conf &
DISPLAY=:0 /build/MIDIVisualizer/build/MIDIVisualizer --midi "$IN_FILE" --size 1920 1080 --preroll 0 --postroll 3 --export "$OUT_VIDEO_ONLY" --format MPEG4

# create timestamp watermark
convert -pointsize 64 -font DejaVu-Sans-Bold -background none -fill white label:"$DATE_SLASH" "$OUT_IMAGE"

# combine video+watermark and audio
ffmpeg -y -loglevel warning -i "$OUT_VIDEO_ONLY" -i "$OUT_IMAGE" -filter_complex "overlay=W-w-10:10" -i "$OUT_AUDIO" -codec:a copy "$OUT_VIDEO"
